tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
brew "ansible"
brew "ant"
brew "autojump"
brew "aws-elasticbeanstalk"
brew "awscli"
brew "bash"
brew "bash-completion"
brew "ccat"
brew "dos2unix"
brew "fish"
brew "fpp"
brew "git"
brew "gradle"
brew "grafana"
brew "httpie"
brew "jq"
brew "kubernetes-cli"
brew "lnav"
brew "mas"
brew "maven"
brew "minikube"
brew "mitmproxy"
brew "mkcert"
brew "mysql@5.7", link: true
brew "neovim"
brew "nss"
brew "nvm"
brew "openjdk@11"
brew "rbenv"
brew "rename"
brew "ruby"
brew "scala"
brew "tmux"
brew "tomcat-native"
brew "tomcat@9"
brew "vagrant-completion"
brew "wget"
brew "yarn"
brew "youtube-dl"
brew "yq"
cask "1password"
cask "betterzip"
cask "deckset"
cask "docker"
cask "eclipse-jee"
cask "encryptme"
cask "firefox"
cask "intellij-idea-ce"
cask "istat-menus"
cask "iterm2"
cask "microsoft-teams"
cask "paw"
cask "pycharm-ce"
cask "sequel-ace"
cask "slack"
cask "the-unarchiver"
cask "vimr"
cask "visual-studio-code"
cask "vlc"
cask "wireshark"
cask "zoom"
mas "Boop", id: 1518425043
mas "Home Assistant", id: 1099568401
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Looking Glass", id: 1602004436
mas "Meeter", id: 1510445899
mas "Microsoft Excel", id: 462058435
mas "Microsoft OneNote", id: 784801555
mas "Microsoft Outlook", id: 985367838
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Remote Desktop", id: 1295203466
mas "Microsoft Word", id: 462054704
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
