name: CI

on:
  # Triggers the workflow on push or pull request events for specific branches
  push:
    branches: [ work ]
  pull_request:
    branches: [ work ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  brew-bundle:
    runs-on: macos-10.15
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      
      # Install Homebrew
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Run Brew Bundle
        run: brew bundle --file $GITHUB_WORKSPACE/Brewfile
